### ISSUE TITLE
Headless browser support

### ISSUE THREAD

**Issue by pedro93** [gatech/xpert#1]
Hi, I read the papers about XPert and its predecessors and this tool sounds extremely useful if it has the same purposes. 
I am developing a tool for cross-browsers rendering and wanted to use XPert to validate it.
In order to do this I was wondering if it was possible to extend the technologies XPert supports to include headless technologies such as phantomJS, SlimerJS, Awesomium or HTMLUnit or the possibility to add them with ease.

**Comment by shauvik** [comment]
Hi @pedro93 Xpert is built on top of [crawljax](https://github.com/crawljax/crawljax), which uses selenium. It might be worth checking if it supports headless and update this project accordingly. I'm open to receiving pull requests!
